### ISSUE TITLE
initial solution should be slot in CocoProblem

### ISSUE THREAD

**Issue by jakob-r** [berndbischl/rcoco#14]
And not necessarily be retrieved after. Just makes things more complicated.

I would remove `c_cocoProblemGetInitialSolution` and put call `coco_problem_get_initial_solution` in `c_cocoSuiteGetNextProblem`.

**Comment by berndbischl** [comment]
hmm. ok. if this is static anyway, then yes

**Comment by berndbischl** [comment]
done
