### ISSUE TITLE
c_cocoOpenSuite: observer options call is wrong

### ISSUE THREAD

**Issue by berndbischl** [berndbischl/rcoco#18]
eg it mentions "random search"
should be rechecked and corrected

**Comment by berndbischl** [comment]
we should figutr out what these options do, possibly look at java interface

**Comment by jakobbossek** [comment]
Dropped observer options for `{c_}cocoOpenSuuite` in PR #29.
Maybe we should add again later the default observers, i.e., *bbob* for *bbob suite*. However, I think it is totally fine to set it up by hand via `cocoInitObserver`.

**Comment by berndbischl** [comment]
that the basic ops work is most important for now

we can always make stuff more convenient later with syntactic sugar.
and create issues about that first, when we notice such inconvenience

**Comment by jakobbossek** [comment]
Observer options are documented in the [coco C docs](http://numbbo.github.io/coco-doc/C/)

**Comment by berndbischl** [comment]
this is outdated, i have opened a clean issue here : #31
