### ISSUE TITLE
cocoOpenSuite: c functions has more options

### ISSUE THREAD

**Issue by berndbischl** [berndbischl/rcoco#28]
what are they? expose to user

**Comment by jakobbossek** [comment]
Copied from the coco c docs:

Possible keys and values for suite_options are:

dimensions: LIST, where LIST is the list of dimensions to keep in the suite (range-style syntax is not allowed here),
dimension_indices: VALUES, where VALUES is a list or a range of dimension indices (starting from 1) to keep in the suite, and
function_indices: VALUES, where VALUES is a list or a range of function indices (starting from 1) to keep in the suite, and
instance_indices: VALUES, where VALUES is a list or a range of instance indices (starting from 1) to keep in the suite.

All of these are already exposed.

**Comment by berndbischl** [comment]
let me check this quickly when your PR is merged, then probably  close

**Comment by jakobbossek** [comment]
Checked. We support all possible options.
