### ISSUE TITLE
runOptimzer should init observer?

### ISSUE THREAD

**Issue by berndbischl** [berndbischl/rcoco#34]
i think if opening the suite does not init and attaches the observer (which makes sense as the observer contains info on the algo, which we dont know then?)

we should at least auto-init the observer in the benchmark / runOptimizer function
that *does* seem intuitive.

**Comment by jakobbossek** [comment]
We should only default to auto-init if No observer is passed.
However, since the observer constructor needs meta Info like algorithm.name we should think about a simple CocoOptimizer wrapper.

**Comment by jakobbossek** [comment]
Added auto-init to default observer, e.g., bbob observer for bbob suite, if no observer is passed to `cocoSuiteRunOptimizer` in 6ce42e7. Check and close please.
