### ISSUE TITLE
cocoInitObserver: show log message where results files are stored

### ISSUE THREAD

**Issue by berndbischl** [berndbischl/rcoco#35]
i wanna see this as a user

**Comment by berndbischl** [comment]
not sure how easy this is, as the final path might be determined inside of coco C code?
then at least show full prefix path

**Comment by jakobbossek** [comment]
I guess the final path is "getwd()/exdata/result.folder". Tired now. Going to check in the next days.

**Comment by berndbischl** [comment]
i would show the absolute path here.
also, if the folder already exists, bbob attaches a counter at the end

drwx------ 4 bischl bischl 4.0K Apr 20 18:28 R_on_bbob
drwx------ 4 bischl bischl 4.0K Apr 20 18:28 R_on_bbob-001
bischl@bischl-x1:~/cos/rcoco/exdata (master) $ 

so the log says: 
"saving to R_on_bbob" but this is wrong as data is stored to the 001 folder

**Comment by berndbischl** [comment]
maybe it would actually be best to ask for the folder path with a getter?

**Comment by jakobbossek** [comment]
Depends on #40

**Comment by jakobbossek** [comment]
Printing absolute prefix path now. IMHO this is fine.

**Comment by jakobbossek** [comment]
Done via 69bd8d2
