### ISSUE TITLE
rcheck does not pass 100%, exit and prints are called in coco C code

### ISSUE THREAD

**Issue by berndbischl** [berndbischl/rcoco#4]
a bit bad, that coco.c calls exit and stdout, and so on.
minimal patches might be needed to we can get on cran

we can do this last

**Comment by berndbischl** [comment]
i patched coco.c

**Comment by mllg** [comment]
I've had already written a little patch script to deal with this.

https://github.com/berndbischl/rcoco/blob/master/inst/scripts/cleanup_source.R

Maybe this should be used, especially because coco.c must regularly be recreated?

**Comment by berndbischl** [comment]
yes, i thought about this, but was too lazy. i actually asked @larskotthoff, whether we can somehow "overwrite" the functions from another file.

but is your script really complete? eg where are you calling Rf_warning?

**Comment by berndbischl** [comment]
have you tested it and compared with the coco output?

**Comment by mllg** [comment]
> but is your script really complete? eg where are you calling Rf_warning?

I've used REprintf to output to the stderr stream. Can also easily be replaced with a call to `[Rf_]warning()`.

**Comment by jakobbossek** [comment]
I think we can close here. Fixed all warnings including.
