### ISSUE TITLE
initobserver and runOptimizer

### ISSUE THREAD

**Issue by berndbischl** [berndbischl/rcoco#40]
a) when i open a suite i have to specify a "name". for initObserver, i have to specify this too.
these 2 should never be different? 
so rather pass the suite to init'Observer? and use the name from it?

b) runOptimizer might simply take a covenience arg "result folder". then the observer is created internally.

actually maybe this is better:
1. openSuite gets a result.folder arg. this specifies the prefix for out path

2. runOptimizer gets a "name" arg for the optimier

3. if no observer is passed to runOptimzer, we autoconstruct it. we take the path from the suite and the optimizer name. if we can we also set the algo name in the observer as a separate observer option

**Comment by nikohansen** [comment]
> when i open a suite i have to specify a "name". for initObserver, i have to specify this too.
these 2 should never be different?

In general I would not make the assumption that the names are always the same. For example, the `bbob-constrained` suite is supposed to be used by default with the "default" `bbob` observer. The other way around, one could easily imagine to use another observer writing different data for the `bbob` suite. It seems reasonable to have for each suite a _default_ observer named if nothing else is specified.

There is a little helper function in the [Python example experiment](
https://github.com/numbbo/coco/blob/master/code-experiments/build/python/example_experiment.py) to achieve exactly this, like:

```python
def default_observers(update={}):
    """return a map from suite names to default observer names"""
    # this is a function only to make the doc available and
    # because @property doesn't work on module level
    _default_observers.update(update)
    return _default_observers
_default_observers = {
    'bbob': 'bbob',
    'bbob-biobj': 'bbob-biobj',
    'bbob-biobj-ext': 'bbob-biobj',
    'bbob-constrained': 'bbob',
    'bbob-largescale': 'bbob',  # todo: needs to be confirmed
    }
```

**Comment by jakobbossek** [comment]
Added internal helper `getDefaultObserver`. However, in the first version we allow the bbob observer only.

**Comment by jakobbossek** [comment]
Done via 69bd8d2
