### ISSUE TITLE
create cocoBecnharkOptimzer 

### ISSUE THREAD

**Issue by berndbischl** [berndbischl/rcoco#7]
should run an optimizer on the complete suite, maybe even parallel

**Comment by berndbischl** [comment]
first prototype is there. for now we need a test, and docs must be checked. rest can be done in other issues

**Comment by jakobbossek** [comment]
each optimizer should be run multiple times on each problem, right?

**Comment by berndbischl** [comment]
> each optimizer should be run multiple times on each problem, right?

well. i think coco does this through the instance concept. 
so each optimitzer should run on each instance once, at least for now

**Comment by jakobbossek** [comment]
I think we can close here.
